2024-08-13 22:42:03,129 Minimum price: 10, Maximum price: 350
2024-08-13 22:42:03,147 Preparing sklearn pipeline
2024-08-13 22:42:03,148 Fitting
Traceback (most recent call last):
  File "/root/Project-Build-an-ML-Pipeline-Starter-1/src/train_random_forest/run.py", line 306, in <module>
    go(args)
  File "/root/Project-Build-an-ML-Pipeline-Starter-1/src/train_random_forest/run.py", line 84, in go
    sk_pipe.fit(X_train, y_train)
  File "/root/miniconda3/envs/mlflow-a76734c8d1d19619b00a1c6854e48cc4ef81c5ff/lib/python3.10/site-packages/sklearn/base.py", line 1152, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/root/miniconda3/envs/mlflow-a76734c8d1d19619b00a1c6854e48cc4ef81c5ff/lib/python3.10/site-packages/sklearn/pipeline.py", line 427, in fit
    self._final_estimator.fit(Xt, y, **fit_params_last_step)
  File "/root/miniconda3/envs/mlflow-a76734c8d1d19619b00a1c6854e48cc4ef81c5ff/lib/python3.10/site-packages/sklearn/base.py", line 1145, in wrapper
    estimator._validate_params()
  File "/root/miniconda3/envs/mlflow-a76734c8d1d19619b00a1c6854e48cc4ef81c5ff/lib/python3.10/site-packages/sklearn/base.py", line 638, in _validate_params
    validate_parameter_constraints(
  File "/root/miniconda3/envs/mlflow-a76734c8d1d19619b00a1c6854e48cc4ef81c5ff/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 96, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'absolute_error', 'squared_error', 'friedman_mse', 'poisson'}. Got 'mae' instead.